### ISSUE TITLE
[김경훈] - 2차 QA & Bug Report

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#112]
### 적 몬스터 관련 내용
-~~적 몬스터들이 예측공격 리스트를 받아오고 순차적으로 공격해야하는데 스턴 검사에서 공격할 몬스터를 받아오지 못해 null값 에러가 걸림.~~
-~~적 몬스터들이 예측공격 리스트만 받아오고 바로 턴을 종료해버림.~~

==>~~디버깅을 통해 공격몬스터를 받아오지 못하는 이유와 바로 턴을 종료해버리는 원인을 찾아야함.~~

### 아군 소환수 관련 내용
- ~~스테이지별로 배수설정이 안되어있음. 스테이지 선택창에서 배수를 넘길 로직 필요~~

==> ~~CheckStage스크립트를 통해 스테이지값을 받아와서 Summon 객체로 넘겨야함.~~

**Comment by LEI-2812** [comment]
## QA 추가사항
### 플레이트 관련 내용
- 소환수가 죽으면 앞으로 당겨지지 않음 (고치지 않아도 전략으로 사용할 수 있을 것 같긴 함)
- ~~첫 턴이 시작되고 공격을 시전하기 전에 재소환을 진행하면 (무슨 이유에서인지 모르겠지만) 재소환된 소환수가 공격하지 못하는 경우가 생김~~

### 가시성 관련 내용
- ~~7스테이지 보스 드래곤 이미지 위치 조정 필요~~

### 편의성 관련 업데이트 희망 사항
- ~~아군 강화, 치유 능력 등 소환수를 골라서 공격을 사용해야 되는 경우, 취소할 수 있는 기능이 있었으면 좋겠음~~
- ~~할 수 있다면 사운드 BGM 기본 음량을 낮추고, SFX 기본 음량을 높이는 것이 필요~~

### 스테이지 관련 추가 작업이 덜 된 부분
- ~~클리어 턴 수 체크 및 클리어 여부 알림창 출력~~
- ~~스테이지별 공격 배수 설정~~

**Comment by LEI-2812** [comment]
### 피드백 내용 진행 상황 표시
- 확인 일자 : 2024/10/28
- 완료된 작업에는 취소선 표기

**Comment by E1phane** [comment]
### QA 버그 추가 사항
- ~~재소환 시 hp 바가 보이지 않는 버그~~
- ~~플레이어의 플레이트가 비어 있는 상태에서 턴 종료 시 적 턴에서 넘어오지 않는 버그~~

**Comment by rudIsland** [comment]
### 버그 수정 사항 24.10.28
- ~~HP바가 0으로 보이는 버그는 수정은 했으나 아직 존재함.~~
- 적 몬스터가 지속데미지를 입고 있을때 힐을 사용하지 않던 버그 수정
- 적 몬스터가 지속데미지를 입고 있을때 예측시에 미리 맞은 상태가 현재 오브젝트에도 적용되어 데미지가 2배로 들어가던 버그 수정

**Comment by rudIsland** [comment]
## 버그 수정 사항 24.11.03
- 흡혈로 지속데미지를 입힐 때 체력이 회복되지 않던 버그 수정
- 소환수가 2마리이고 소환수들간에 현재 체력이 30% 이상 날경우 현재체력이 가장 높은 대상에게 흡혈을 사용하도록 수정
- 재소환시 상태창 체력이 0으로 보이던 버그 수정
- 토끼로 아군에게 힐 사용시 적 플레이트의 선택에 대한 유효성검사를 먼저 해버려서 힐이 안되던 버그 수정

**Comment by LEI-2812** [comment]
### 이슈 닫음
✅QA 피드백 및 수정 작업 완료
