### ISSUE TITLE
[김태양] - 3차 QA & Bug Report

### ISSUE THREAD

**Issue by E1phane** [LEI-2812/SUMMONER_Repo#142]
### 스테이지 관련 사항
- ~~current turn 줄 넘김 이슈~~
    - ~~전투 씬 내의 current turn이 10부터 줄넘김이 일어남.~~
    => ~~current turn의 글씨 크기 조정 필요해 보임~~
- ~~7스테이지 클리어 후 에필로그로 넘어가지 않음~~
  => ~~올바르게 연결되어 있는 지 확인 필요~~

**Comment by rudIsland** [comment]
## QA 이슈
### 프롤로그
- ~~프롤로그 마지막 씬 넘어가기 직전에 첫번째 이미지가 잠깐 등장하고 넘어가는 현상이 있음.~~

### 인게임 내 이슈
- ~~소환(재소환)시 소환수 선택 판넬창에 슬라임이 등장하고 있는 현상이 있음. 실제로 공격도 하고 스킬도 사용함.~~
- ~~3 스테이지부터 난이도가 너무 쉬워짐. 적 몬스터의 스탯을 높이던가 턴을 줄이던가 배수 값을 낮출필요가 있음~~
- ~~7스테이지 클리어시 에필로그로 넘어가지 않음.~~
- ~~일반공격과 특수공격이 한 턴에 동시에 공격 가능한 현상이 있음.~~

**Comment by LEI-2812** [comment]
### 스토리 출력 시스템 관련 사항
- ~~프롤로그에서 맨 마지막 대사 출력 이후에 첫 번째 이미지가 출력됨~~
- ~~스토리 출력 화면에서 페이드아웃 전환이 되지 않음~~

### 스테이지 관련 사항
- ~~'처음부터'를 선택하면 모든 스테이지가 선택 가능해짐 (현재는 테스트 때문에 열어놓음)~~
- ~~7스테이지 클리어 이후의 화면 출력이 없음~~
  - ~~순서 : 7스테이지 클리어 알림창 → 에필로그 출력 → Thank Screen 출력 → 처음 화면 이동~~
  - ~~화면 별로 페이드인/아웃 효과가 들어가야 함 (굳이 넣지 않아도 괜찮습니다)~~

### 전투 시스템 관련 사항
- 3스테이지에서 1번 플레이트의 몬스터가 죽었을 때 뒤의 몬스터가 앞으로 당겨오지 않는 현상 발생
- ~~소환수가 일반 공격과 특수 공격을 모두 사용할 수 있는 경우가 발생~~
  - ~~발생하는 스테이지 : 3스테이지, 4스테이지, 7스테이지~~

### 화면 출력 및 플레이 관련 사항
- ~~턴 수 체크 패널에서 'Current Turn'의 숫자가 2자리를 넘어가면 두 줄로 출력되는 경우 생김~~
  - ~~폰트 크기를 작게 줄여 출력할 예정~~
- ~~전투 시스템 플레이에 키보드를 사용하지 않기 때문에 설정 창의 GamePlay 부분이 필요 없어짐~~
  - ~~설정의 내용을 삭제하거나, 키보드의 키를 버튼에 할당하거나 둘 중 하나 해야 함~~
  - 설정을 그대로 두고 구현하지 않는 방법도 있습니다:).. <해당 방식 채택>

### 사운드 관련 사항
- 공격 효과음이 간혹가다 출력되지 않는 현상 발생 (씹히는 것 같음)

### 보완 및 수정 희망사항
- ~~상태이상이 걸리면 상태창에서 확인할 수 있도록 했으면 좋겠음~~
  - ~~원래 기획서에 존재했던 내용인데 구현하면서 빠졌음~~
  - ~~밑에 작게 이미지를 띄우거나, 몹의 색을 변경시키는 정도의 변경이 있으면 알기 쉬울 것 같음~~

**Comment by rudIsland** [comment]
### 반드시 고쳐야할 것
- ~~슬라임이 소환 선택창에 나타나는 현상~~
- ~~7스테이지 끝나고 에필로그로 넘어가야하는데 넘어가지 않는 현상~~
- ~~공격이 일반,특수 둘다 가능한 현상~~
- ~~턴 수가 2줄되면 줄바꿈 되버리는 현상~~
- 몬스터가 앞 당겨지지 않는 현상

### 가능하다면 구현할 기능
- ~~상태이상 걸린 소환수 시각적 표시~~

**Comment by rudIsland** [comment]
### 24-11-08 수정사항
## 3차QA 관련 수정
1. current Turn 줄바꿈 이슈 
=> 텍스트 길이가 충분하지 않아서 overflow로도 줄바꿈이 되버림. 텍스트 오브젝트 길이를 300-> 350으로 변경

2. 특수공격과 일반공격이 동시에 가능한 현상
 => 스턴여부와 공격가능 여부를 and연산으로 해놔서 특수공격시에 조건에 맞으면 공격이 가능한 현상이 있었는데 일반공격에도 똑같이 하여 or연산으로 수정하였음

3. 이어하기 기능 
StageController에는 현재 진행중인 스테이지 번호값을 넣고, 저장되는 값은 Prefs로 저장하고 가져오게 구현

## 기존 로직 수정사항
4. 해상도와 화면크기 prefs 해상도와 화면크기도 prefs로 했으나 변경이 잘 되는지는 빌드해봐야 확실할듯함.

**Comment by LEI-2812** [comment]
### 피드백 내용 진행 상황 표시
- 확인 일자 : 2024/11/18
- 완료된 작업에는 취소선 표기

**Comment by LEI-2812** [comment]
### 추가 QA 사항
- 고양이의 특수 공격 모션이 없음
- 7스테이지의 보스 몬스터가 사라졌는데 게임이 끝나지 않음 (한 번 더 공격을 해야 사라지면서 클리어됨)
- 간혹가다 몬스터의 색이 검은색으로 변하고 원래대로 돌아오지 않는 경우가 생김 (공격 시 검은색으로 변했다가 풀리지 않는 것 같음)
  → 다른 색으로 변한 후에는 원래대로 돌아옴
- ~~'이어서' 버튼의 알림창 폰트 미적용~~
