### ISSUE TITLE
시스템 디자인 기획서 질문있습니다! (24.08.20)

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#4]
- 소환로직
=> 6 종류 소환수 중 1개를 "랜덤"소환인데 랜덤인 이유가 궁금합니다.

- 적 공격 알고리즘
=> 치유스킬 존재 여부 파악 내용에 30% 이하인 "적군"이 플레이어 기준으론 적이지만 다른 내용에선 적의 시점으로 적혀있어서 오타라 의심됩니다.

**Comment by LEI-2812** [comment]
### QA
- 소환로직 랜덤 설정
    원래 기획에는 하급, 중급, 상급 소환수를 두고 각각 소환 시 사용하는 마나 양을 다르게 설정할 예정었습니다만..
    하다 보니까 최대 마나 양을 얼마로 설정할지, 소환수별로 다른 공격 방식을 어떻게 나눠야 할지도 애매해지더라구요.
    3개월동안 어떻게든 완성을 해야 하는 프로젝트 특성 상 메커니즘 간소화를 위해서 차라리 랜덤이 낫겠다 생각했습니다🥲

    하지만 만약 좋은 의견이 있으시거나, 메커니즘 간소화를 할 수 있는 방법이 있으시면 언제든지 말씀해주세요:)
    아직 기획서 작성 단계니까 수정할 수 있습니다..!
    
- 적 공격 알고리즘
    확인한 결과 그쪽만 검수를 안 하고 내보낸 것 같아요ㅠㅜ
    수정해서 다시 올려놓도록 하겠습니다!
    이외에 적 공격 알고리즘 전체 내용은 모두 적의 시점에서 작성되었으니 혹시 또 다른 오타나 문법적 실수가 있을 땐 얼마든지 물어봐주세요😊

**Comment by rudIsland** [comment]
소환로직은 일단 랜덤으로 가보고 개발과정이나 그 전에 수정될 가능성이 있다라고 알아두겠습니다
