### ISSUE TITLE
랜덤 소환 비율 변경 여부 의견을 묻고 싶습니다🤓 (24.08.22)

### ISSUE THREAD

**Issue by LEI-2812** [LEI-2812/SUMMONER_Repo#5]
지금은 시스템 기획서에 적힌 내용대로 소환수 6마리 중 한 마리를 랜덤으로 소환하는 방식을 채택했었습니다만, 레벨 디자인을 하다보니 약간의 비율 설정이 필요하다고 생각됩니다.
또한, 마나의 개수가 존재하는 이유를 현재까지는 단순히 소환수를 채우기 위한 것으로 쓰는 방식 말고는 설명할 수가 없어요.
그 점이 좀 걸려서 마나를 아끼는 선택 또한 할 수 있도록 만들어볼까 싶은데 한 번 의견을 들어보고 싶습니다:)
    
만약 비율을 변경한다고 하면 다음과 같이 변경할 것 같습니다.
- 소환수에 등급을 매기고 이에 따라 소환 시 랜덤으로 등장할 확률을 조정한다. (하급이 더 많이, 상급이 더 적게 나오도록)
- 가지고 있는 마나의 개수가 많다면 소환 시 더 좋은 등급이 등장할 확률이 높아진다.

이외에도 다른 좋은 의견이 있으면 무엇이든지 코멘트 달아주세요!

**Comment by rudIsland** [comment]
- 마나의 존재
>스킬에도 마나 소모량을 적용시켜서 좀더 유의미하게 마나를 활용해도 좋을 것 같습니다.

- 소환의 랜덤로직
>롤토체스 리롤처럼 레벨에따라 상점에 나타나는 등급의 확률을 소환에 적용시켜서 소환할 때 만약 1~5등급의 소환수가 있다면
1마나소모: 1등급:70% 2등급: 20% 3등급:5% 4등급:3% 5등급: 2%
2마나소모: 1등급:40% 2등급:40% 3등급:10% 4등급:6% 5등급:4%
3마나소모: 1등급25% 2등급: 25% 3등급: 30% 4등급:12% 5등급:8%
4마나소모: 1등급: 20% 2등급: 20% 3등급: 30% 4등급: 20% 5등급:10%
5마나소모: 1등급:15% 2등급:20% 3등급: 25% 4등급:25% 5등급 15%
대강 이런 확률로 높이고,

+) 마나를 하스스톤처럼 최대마나량을 1씩 증가시키면서 자기턴에는 마나가 모두 충전되고 소환과 스킬을 전략적으로 쓰게하는 방법도 생각해봤습니다

**Comment by LEI-2812** [comment]
스킬에도 마나 소모량이 생기면 소환 시 사용되는 마나와 스킬 사용 마나가 공유되면서 더 이상 턴 종료 후 1씩 충전되는 형태를 사용하기 어려울 것 같습니다🥲
예를 들어 마나의 총량을 10이라 잡고, 소환을 위해 1을 사용한 뒤 스킬 사용에서 또다시 1~3을 사용하는 형태로 공격하게 되면 나중에는 마나 고갈이 발생해 아무 공격도 하지 못하고 턴을 종료하게 되는 경우가 생기지 않을까요?

물론 이 경우에는 예시로 들어주신 하스스톤 같은 형태로 최대 마나량이 증가하도록 하면 어느정도 해결됩니다.
두 방식 중에서 더 구현하기 쉬운 쪽으로 가야할 것 같아요:)

어느 쪽이 좀 더 괜찮으신가요?

**Comment by LEI-2812** [comment]
아 참고로 지금은 첫 번째 방식대로 공격계수를 짜놓았습니다!
만약 두 번째 방식을 택하면 공격계수도 조정할 것 같아요🙂

**Comment by E1phane** [comment]
소환 시 확률에 따라 소환되는 경우에는 자신의 운에 따라서는
저등급 소환수들만 나올 수도 있을 수도 있다고 생각합니다.

확률에 따라 소환을 하되, 소환 결과 나올 소환수를 미리 보여주고
그 결과를 바꾸는 데 마나를 소모하게 하면 어떨까요?
예를 들어 결과를 바꿀 때마다 마나의 소모값을 1씩 늘린다면 원하는 소환수를 뽑을 확률도 생기고
마나의 소모도 원하는 만큼 생각해서 할 수 있다고 생각합니다.

**Comment by LEI-2812** [comment]
즉, 're-roll'같은 개념이네요.
마나 소모에도 효과적이어 보여서 괜찮은 것 같아요!

다만, 현재 설정해놓은 최대 마나 개수가 3이기 때문에, 이를 더 늘려서 10~20 사이 정도로 적절하게 결정하면 플레이어의 소환 전략을 더 풍부하게 이끌어낼 것 같습니다.
기획서는 이 메커니즘대로 한 번 작성해보도록 하겠습니다:)
의견 내주셔서 감사합니다!
