### ISSUE TITLE
레벨 디자인 기획서 표기오류 질문있습니다! (24.08.26)

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#6]
등장개체 2번표와 3번표에 뱀과 여우 특수공격이 서로 엇갈려있습니다.

-2번표
뱀: 아군 공격력 상승 / 여우: 적에게 중독상태 걸기
-3번표
뱀: 상대 풀피기준 10% / 여우: 공격력 20% 상승

이렇게 표기되어있습니다! 어느쪽이 맞는걸까요?

**Comment by LEI-2812** [comment]
3번 표의 내용이 맞습니다!
2번 표의 표기 오류는 고쳐서 재업로드 했습니다🥲
