### ISSUE TITLE
상태이상 공격 적용시점 질문있습니다

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#67]
레벨 디자인 7페이지에 상태이상을 보면 중독, 혼란, 저주, 흡혈, 화상이 있습니다.

저주,혼란,흡혈의 경우 사용 직후 적용된다고 생각이 들지만
중독, 화상의 적용시점이 확실치 않아 질문드립니다.

5가지 모두 기준을 잡아주시면 좋겠습니다.

**Comment by LEI-2812** [comment]
상태이상 스킬은 상대 진영에 사용하고 난 후, 해당 상태에 걸린 몹들은 그 턴에 첫 데미지를 입게 됩니다.
따라서 일괄적으로 사용 직후부터 바로 적용된다고 할 수 있습니다.

참고로 데미지에 관련된 부분은 추후 수치 조정이 들어갈 수 있다는 점을 고려해서 구현하면 좋을 것 같습니다:)
