### ISSUE TITLE
새로 추가된 몬스터의 특수스킬 <보호막> 관련 질문이있습니다.

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#80]
새로 추가되서 조건부를 확실치 못해서 질문합니다.
보호막은 타겟지정인가요 따로 로직이 있는건가요
지금 현재 타겟지정, 가까운적, 전체공격 로직으로 구분지어서 특수스킬들을 구현중입니다.

**Comment by LEI-2812** [comment]
보호막은 무조건 자기 자신에게만 적용됩니다.
다른 타겟을 지정하거나 전체에게 보호막을 씌우는 건 불가능합니다:)
