### ISSUE TITLE
지속시간 질문입니다.

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#83]
뱀의 독성 지속시간의 경우 3턴(받는 횟수) / 쿨타임도 3턴입니다.
스킬을 사용하면 즉시 데미지를 입죠? 그럼 **지속시간은 2턴(2번)** 남게되고  / **쿨타임은 저번 질문대로 3턴**이 남습니다.
다음턴 시작할때 데미지를 입으면 남은 **지속시간 (1턴)1번** / **쿨타임은 2턴**이 남습니다.
다다음턴이 시작하면 데미지를 입고나서 **상태이상이 풀리**고 / **쿨타임은 1턴**이 남습니다.
다음턴이 시작하면 **지속시간은 없고**, 이때 **쿨타임이 풀립**니다.

정리해보면 (상태이상턴 / 쿨타임턴)
사용턴(데미지입음2/3)
다음턴(데미지입음1/2)
다다음턴(데미지입고풀림/1)
다다다음턴(없음/쿨타임 줄어들어서 즉시 사용가능) 이 될테죠?

근데 만약 같은 독성을 덮어 씌우게되면 데미지를 입히지 않고 3턴으로 갱신되서
사용한턴(이미 데미지를 입은상태라서 지속시간만 3턴으로 갱신 / 3턴)
다음턴(2턴 / 2턴)
다다음턴(1턴 / 1턴)
다다음턴(데미지 받고풀림 / 0턴되서 즉시사용가능)

이렇게 생각이 드는데
요점은 같은 속성의 스킬을 사용하면 <<데미지를 입혀서 2턴만 갱신되느냐, 그냥 덮어씌우고 3턴만 갱신되느냐>> 입니다.

**Comment by LEI-2812** [comment]
상태이상 공격은 기본적으로 하나만 걸릴 수 있습니다.
덮어 씌우는 것도 불가능하고, 두 개의 상태이상을 같이 걸리는 것도 불가능합니다.
같은 상태 이상도 똑같이 적용되기 때문에 이 점 참고해주시면 감사하겠습니다!
