### ISSUE TITLE
연속 공격이 특수스킬 포함해서 연속인가요 일반공격만 연속인가요

### ISSUE THREAD

**Issue by rudIsland** [LEI-2812/SUMMONER_Repo#84]
등급별 연속공격을 개발중인데
만약 특수공격까지 사용가능하면 모든 공격의 범주에서 연속이 가능한건가요 아님 일반공격에 대해서만 연속공격인건가요

**Comment by LEI-2812** [comment]
모든 공격 범주에서 연속 공격을 하는 겁니다!
예를 들어 적이 상태이상 : 흡혈 공격을 하고 연속 공격이 가능할 시 상태이상 : 화상 공격을 할 수도 있어요:)
