### ISSUE TITLE
[김민선] - 1차 QA & Bug Report

### ISSUE THREAD

**Issue by LEI-2812** [LEI-2812/SUMMONER_Repo#89]
### 전체 스테이지 관련 내용
- ~~1스테이지의 적이 원래는 슬라임 2마리인데, 3마리로 출력됨~~
  - ~~3번째 플레이트의 적 이미지 할당을 뺐는데, 흰색 네모로 같이 출력되어 수정 필요~~
  - ~~아직 스테이지 구현이 덜 된 부분이기 때문에 스테이지 수정할 때 같이 진행~~ 

### 소환수 관련 사항
- ~~이미 공격한 소환수를 재소환하면 공격이 계속 진행됨~~
  - ~~해당 플레이트에서 공격을 진행했다면 아무리 재소환해도 공격은 다시 할 수 없도록 설정해야 함~~
- ~~소환수 하나 당 1번만 공격할 수 있는데, 일반 공격과 특수 공격을 둘 다 사용할 수 있음~~
  - ~~둘 중 하나의 공격만을 사용하도록 해야 함 (예측 시스템 역시 둘 중 하나의 공격을 사용하도록 하기 때문)~~

### 몬스터 관련 사항
- ~~앞의 몬스터가 죽으면 다음 몬스터가 1번 플레이트로 이동해야 함~~
- ~~몬스터가 연속 공격을 발동시킨 다음, 공격하지 않고 그대로 턴이 종료되는 경우가 생김~~
- ~~몬스터가 보호 공격을 사용할 때 '선택된 plate에 대상이 없습니다'라는 디버그 메시지와 함게 턴이 종료되는 경우가 생김~~

### 가시성 관련 개선 사항
- 보호막이 현재 적용 중인지 확인이 불가능함
  - 디버그 메시지로만 현재 얼만큼의 보호막이 남아있는지 수치를 확인할 수 있음
  - 이를 가시화해 보호막 이미지를 몬스터 이미지 위에 띄우면 될 것 같음
- ~~상태창이 턴 진행 시에 띄워져 있으면 체력 수치가 갱신되지 않음 (고쳐도 되고, 안 해도 상관 없음)~~
- ~~소환수와 적 이미지의 규격이 서로 달라 체크 필요함~~

**Comment by rudIsland** [comment]
### 수정한 내용

- 적 몬스터 배치는 레벨 디자인 기획서에 내용대로 배치해두었습니다. 이미지가 아직 프리팹에 할당되어있지 않아서 씬을 돌리게되면 흰색 네모로 밖에 안나옵니다. **이미지 할당은 Assest폴더에 프리팹에 할당해주시면 모두 적용됩니다**


### 버그 관련 추후 고칠내용
- ~~전체적으로 소환수에 대해 문제인데 
먼저, 플레이트에서 공격여부를 묻게된다면 결국 같은 소환수가 2번 공격할 수 있는 방법이 생기게 됩니다. 그렇기에 소환수 자체에 소환된 턴에 공격하지 못하도록 수정하겠습니다.~~

- ~~소환수 하나당 한 번 공격 역시 플레어어의 소환수들에 대해서만 일반 공격과 특수공격을 사용시 다른 공격을 하지 못하게 하도록 하겠습니다.~~

~~앞의 몬스터가 죽으면 다음 몬스터가 앞 플레이트로 이동하는 것도 체력이 0이되면 플레이트를 검사하여 빈곳을 채우는 식으로 앞으로 이동시키는 로직을 추후에 추가하도록 하겠습니다. 아직 미구현입니다.~~

- 가시성에 대해서는 아직 전체적으로 미구현상태입니다. 보호막과 무적에 대한 이미지나 체력바에 색상을 다르게 하여 표현해보도록 해보겠습니다.

- ~~상태창이 지금은 한번 클릭한 플레이트의 소환수를 계속 띄어놓고 있을겁니다. 공격 버튼 클릭시 상태창을 닫도록 하겠습니다. + 공격받을 시 상태창을 업데이트시키겠습니다.~~

- 소환수와 적 이미지 규격은 저희도 몬스터마다 규격이 모두 달라서 각 크기 값을 알아내야 할 것 같습니다.

**Comment by LEI-2812** [comment]
### 이미지 규격 관련 개선 방향
- 이미지 규격이 소환수와 적 모두 다 다르게 설정되어 있는 점은 인지한 상태이며, 이를 고치기 위해서 소환수의 이미지와 적 이미지의 규격을 통일할 수 있도록 그래픽 작업을 할 예정입니다.
- 현재 소환수 이미지는 규격을 통일해 작업한 아트가 올라가 있는 상태이나, 이미지의 크기가 작아 수정을 거쳐야 할 것 같습니다. 이 점 참고 부탁드립니다.

**Comment by LEI-2812** [comment]
### 피드백 내용 진행 상황 표시
- 확인 일자 : 2024/10/21
- 완료된 작업에는 취소선 표기

**Comment by LEI-2812** [comment]
### 이슈 닫음
✅QA 피드백 및 수정 작업 완료
